coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
